[package]
name = "hkx-extractor"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
glam = "0.25"
log = "0.4"
simplelog = "0.12"
tokio = { version = "1", features = ["full"] }
